name: Publish to VS Marketplace

# Triggered by a new GitHub Release being published. It expects to find
# two .visx assets in the Release:
#    EditorGuidelines.vsix and
#    EditorGuidelines.Dev17.vsix

on:
  release:
    types: [published]
#  workflow_dispatch:

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Fetch latest release assets
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: EditorGuidelines.vsix

      - name: Publish to VS marketplace
        uses: CalvinAllen/action-vs-marketplace-publish@v1
        with:
          marketplace-pat: ${{ secrets.vs_pat }}
          publish-manifest-path: marketplace/publishManifest.json
          vsix-path: EditorGuidelines.vsix

      - name: Fetch latest release assets
        uses: dsaltares/fetch-gh-release-asset@1.1.1
        with:
          file: EditorGuidelines.Dev17.vsix

      - name: Publish Dev17 to marketplace
        uses: CalvinAllen/action-vs-marketplace-publish@v1
        with:
          marketplace-pat: ${{ secrets.vs_pat }}
          publish-manifest-path: marketplace/publishManifest.Dev17.json
          vsix-path: EditorGuidelines.Dev17.vsix
